# Generated by Django 2.2.4 on 2019-09-03 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('useremail', models.EmailField(max_length=255, unique=True)),
                ('userpassword', models.CharField(max_length=255)),
                ('usertoken', models.CharField(blank=True, max_length=255, null=True)),
                ('userfullname', models.CharField(max_length=255)),
                ('rolid', models.UUIDField()),
                ('userleveltype', models.IntegerField()),
                ('userestado', models.IntegerField()),
            ],
            options={
                'db_table': '"v1"."usuarios"',
            },
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('accionid', models.UUIDField(default=uuid.UUID('d12a0f38-167b-4abf-a93b-2c81f50733f3'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': '"v1"."acciones"',
            },
        ),
        migrations.CreateModel(
            name='DatosContexto',
            fields=[
                ('dataid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hdxtag', models.CharField(max_length=20)),
                ('datavalor', models.CharField(max_length=20)),
                ('datatipe', models.IntegerField()),
                ('proyid', models.UUIDField()),
            ],
            options={
                'db_table': '"v1"."datos_contexto"',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('desiid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desidescripcion', models.CharField(max_length=1000)),
                ('userid', models.UUIDField()),
            ],
            options={
                'db_table': '"v1"."decisiones"',
            },
        ),
        migrations.CreateModel(
            name='DecisionProyecto',
            fields=[
                ('desproid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proyid', models.UUIDField()),
                ('desiid', models.UUIDField()),
            ],
            options={
                'db_table': '"v1"."decisiones_proyecto"',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.UUIDField()),
                ('proyid', models.UUIDField()),
                ('miembroestado', models.IntegerField()),
            ],
            options={
                'db_table': '"v1"."equipos"',
            },
        ),
        migrations.CreateModel(
            name='FuncionRol',
            fields=[
                ('funcrolid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rolid', models.UUIDField()),
                ('accionid', models.CharField(max_length=255)),
                ('funcrolestado', models.IntegerField()),
                ('funcrolpermiso', models.IntegerField()),
            ],
            options={
                'db_table': '"v1"."funciones_rol"',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('instrid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instridexterno', models.CharField(max_length=255)),
                ('instrtipo', models.IntegerField()),
                ('instrnombre', models.CharField(max_length=255)),
                ('instrdescripcion', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'db_table': '"v1"."instrumentos"',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proynombre', models.CharField(max_length=255)),
                ('proydescripcion', models.CharField(max_length=1000)),
                ('proyidexterno', models.CharField(max_length=255)),
                ('proyfechacreacion', models.DateTimeField()),
                ('proyfechacierre', models.DateTimeField(blank=True, null=True)),
                ('proyestado', models.IntegerField()),
            ],
            options={
                'db_table': '"v1"."proyectos"',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rolname', models.CharField(max_length=50)),
                ('roldescripcion', models.CharField(max_length=255)),
                ('rolestado', models.IntegerField()),
            ],
            options={
                'db_table': '"v1"."roles"',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tareid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tarenombre', models.CharField(max_length=255)),
                ('taretipo', models.IntegerField()),
                ('tarerestricgeo', models.CharField(max_length=1000)),
                ('tarerestriccant', models.IntegerField()),
                ('tarerestrictime', models.CharField(max_length=1000)),
                ('instrid', models.UUIDField()),
                ('proyid', models.UUIDField()),
            ],
            options={
                'db_table': '"v1"."tareas"',
            },
        ),
    ]
