# Generated by Django 2.2.4 on 2019-09-04 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='userpassword',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='accion',
            name='accionid',
            field=models.UUIDField(default=uuid.UUID('50258478-ee9f-42e7-90bc-4e70fc047c0b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
